<a href="https://colab.research.google.com/github/txaugusto/Udemay-Data-Science/blob/main/Amostragem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import random

In [4]:
dataset = pd.read_csv('census.csv')

Amostragem Aleatoria Simples

In [5]:
dataset.shape
dataset.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
df_amostra_aleatoria_simples = dataset.sample(n=100, random_state=1)
df_amostra_aleatoria_simples.shape
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

In [7]:
def amostra_aleatoria (dataset, amostras):
  return dataset.sample(n = amostras, random_state = 1)

df_amostra_aleatoria_simples = amostra_aleatoria(dataset, 100)
df_amostra_aleatoria_simples.shape
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

Amostragem Sistematica

In [8]:
np.arange(68, len(dataset), step=325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [10]:
def amostragem_sistematica(dataset, amostras):
  intervalo = len(dataset) // amostras
  print(intervalo)
  random.seed(1)
  inicio = random.randint(0, intervalo)
  print(inicio)
  indices = np.arange(inicio, len(dataset), step = intervalo)
  print(indices)
  amostra_sistematica = dataset.iloc[indices]
  print(amostra_sistematica)
  return amostra_sistematica

teste = amostragem_sistematica(dataset, 100)

325
68
[   68   393   718  1043  1368  1693  2018  2343  2668  2993  3318  3643
  3968  4293  4618  4943  5268  5593  5918  6243  6568  6893  7218  7543
  7868  8193  8518  8843  9168  9493  9818 10143 10468 10793 11118 11443
 11768 12093 12418 12743 13068 13393 13718 14043 14368 14693 15018 15343
 15668 15993 16318 16643 16968 17293 17618 17943 18268 18593 18918 19243
 19568 19893 20218 20543 20868 21193 21518 21843 22168 22493 22818 23143
 23468 23793 24118 24443 24768 25093 25418 25743 26068 26393 26718 27043
 27368 27693 28018 28343 28668 28993 29318 29643 29968 30293 30618 30943
 31268 31593 31918 32243]
       age      workclass  final-weight      education  education-num  \
68      49   Self-emp-inc        191681   Some-college             10
393     34      State-gov         98101      Bachelors             13
718     22        Private        214399   Some-college             10
1043    44        Private        167005      Bachelors             13
1368    52        Private        152234        HS-grad              9
...    ...            ...           ...            ...            ...
30943   33        Private         48010   Some-college             10
31268   43        Private        306440    Prof-school             15
31593   37        Private        171968      Assoc-voc             11
31918   26        Private        154571   Some-college             10
32243   33        Private        198069        HS-grad              9

            marital-status          occupation    relationship  \
68      Married-civ-spouse     Exec-managerial         Husband
393     Married-civ-spouse     Exec-managerial         Husband
718          Never-married               Sales       Own-child
1043    Married-civ-spouse     Exec-managerial         Husband
1368    Married-civ-spouse     Exec-managerial         Husband
...                    ...                 ...             ...
30943             Divorced     Exec-managerial       Unmarried
31268        Never-married      Prof-specialty   Not-in-family
31593   Married-civ-spouse        Adm-clerical         Husband
31918        Never-married   Machine-op-inspct   Not-in-family
32243        Never-married   Machine-op-inspct   Not-in-family

                      race      sex  capital-gain  capital-loos  \
68                   White     Male             0             0
393                  White     Male          7688             0
718                  White   Female             0             0
1043                 White     Male          7688             0
1368    Asian-Pac-Islander     Male         99999             0
...                    ...      ...           ...           ...
30943                White   Female             0             0
31268                White     Male             0             0
31593                White     Male             0             0
31918   Asian-Pac-Islander     Male             0             0
32243                White     Male             0             0

       hour-per-week  native-country  income
68                50   United-States    >50K
393               45               ?    >50K
718               15   United-States   <=50K
1043              60   United-States    >50K
1368              40           Japan    >50K
...              ...             ...     ...
30943             40   United-States   <=50K
31268             66          France   <=50K
31593             40   United-States   <=50K
31918             45   United-States    >50K
32243             65   United-States   <=50K

[100 rows x 15 columns]