<a href="https://colab.research.google.com/github/txaugusto/Udemay-Data-Science/blob/main/Amostragem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import random

In [4]:
dataset = pd.read_csv('census.csv')

Amostragem Aleatoria Simples

In [5]:
dataset.shape
dataset.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
df_amostra_aleatoria_simples = dataset.sample(n=100, random_state=1)
df_amostra_aleatoria_simples.shape
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

In [7]:
def amostra_aleatoria (dataset, amostras):
  return dataset.sample(n = amostras, random_state = 1)

df_amostra_aleatoria_simples = amostra_aleatoria(dataset, 100)
df_amostra_aleatoria_simples.shape
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

Amostragem Sistematica

In [8]:
np.arange(68, len(dataset), step=325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [28]:
def amostragem_sistematica(dataset, amostras): # funçao para selecionar X amostras
  intervalo = len(dataset) // amostras # calcula o intervalo \ formula. população / qtd amostras desejada = inteiro da divisão
  print(f"intervalo {intervalo}")
  random.seed(1) # random.seed() 0 ou 1 para trazer o mesmo resultado sempre
  inicio = random.randint(0, intervalo) # seleciona um numero aleatorio entre 0 e o intervalo
  print(f"inicio {inicio}")
  indices = np.arange(inicio, len(dataset), step = intervalo) # np.arange serve como for para iterar e armazenar na variavel os indices resultantes em um array
  print(f" indices {indices}")
  amostra_sistematica = dataset.iloc[indices] # com o valor da varivel indice, uso iloc[] para selecionar apenas os indices da variavel indices na tabela mãe e armazeno em amostra_sistematica
  return amostra_sistematica # retorna o resultado de amostra_sistematica para a função

df_teste = amostragem_sistematica(dataset, 10) # chama a função, passa a tabela toda e quantas amostras deseja retornar e armazena em df_teste
df_teste

intervalo 3256
inicio 550
 indices [  550  3806  7062 10318 13574 16830 20086 23342 26598 29854]

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
550,46,Self-emp-not-inc,245724,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,50,United-States,<=50K
3806,32,Federal-gov,111567,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
7062,31,Federal-gov,139455,Bachelors,13,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,Cuba,<=50K
10318,35,Federal-gov,287658,Some-college,10,Married-civ-spouse,Protective-serv,Husband,Black,Male,0,0,40,United-States,>50K
13574,32,Private,83253,Some-college,10,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,60,United-States,<=50K
16830,26,Private,101027,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,<=50K
20086,38,Private,273640,HS-grad,9,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
23342,21,?,380219,Some-college,10,Never-married,?,Own-child,Black,Female,0,0,40,United-States,<=50K
26598,23,?,87569,Some-college,10,Separated,?,Not-in-family,White,Female,0,0,40,United-States,<=50K
29854,35,Private,316141,Some-college,10,Divorced,Prof-specialty,Unmarried,White,Female,7443,0,40,United-States,<=50K